image: "gitlab-registry.isae-supaero.fr/dragoon/komodo:406e2b0c1ca04443d9219fa2fbb07f62dc81c796"

stages:
  - fmt
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web'
    - if: $CI_COMMIT_MESSAGE =~ /^(draft|no-ci):/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: ($CI_PIPELINE_SOURCE == "push") && ($CI_COMMIT_BRANCH == "main")
    - if: $CI_COMMIT_REF_PROTECTED == "true"

fmt:
  stage: fmt
  script:
    - ./make.rs ci --fmt

test:
  stage: test
  needs:
    - fmt
  script:
    - ./make.rs ci --test
    - ./scripts/check-lock-file.sh
