image: "gitlab-registry.isae-supaero.fr/dragoon/komodo:bcb0e6b5f73420762f6208700a43291e0066c2c3"

stages:
  - fmt
  - test

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^(draft|no-ci):/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: ($CI_PIPELINE_SOURCE == "push") && ($CI_COMMIT_BRANCH == "main")

fmt:
  stage: fmt
  script:
    - ./make.rs fmt --check

test:
  stage: test
  needs:
    - fmt
  script:
    - ./make.rs version
    - ./make.rs check
    - ./make.rs clippy
    - ./make.rs test
