image: "rust:latest"

stages:
  - fmt
  - test

variables:
  RUSTUP_CHANNEL: "1.75"
  NUSHELL_ARCH: "x86_64-unknown-linux-musl"
  NUSHELL_VERSION: "0.89.0"

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^(draft|no-ci):/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: ($CI_PIPELINE_SOURCE == "push") && ($CI_COMMIT_BRANCH == "main")

fmt:
  stage: fmt
  before_script:
    - rustup install "$RUSTUP_CHANNEL"
    - rustup component add rustfmt --toolchain "$RUSTUP_CHANNEL"

    - rustup default "$RUSTUP_CHANNEL"

  script:
    - cargo fmt --all -- --check

test:
  stage: test
  needs:
    - fmt
  before_script:
    - apt update --yes
    - apt upgrade --yes
    - apt install protobuf-compiler --yes

    - rustup install "$RUSTUP_CHANNEL"
    - rustup component add clippy --toolchain "$RUSTUP_CHANNEL"

    - rustup default "$RUSTUP_CHANNEL"

    - rustup --version
    - rustup show --verbose
    - rustc --version
    - cargo --version
    - cargo clippy --version

    - export NUSHELL_BUILD="nu-$NUSHELL_VERSION-$NUSHELL_ARCH"
    - export PATH="/tmp/:$PATH"

    # install Nushell
    - curl -fLo /tmp/nu.tar.gz "https://github.com/nushell/nushell/releases/download/$NUSHELL_VERSION/$NUSHELL_BUILD.tar.gz"
    - tar xvf /tmp/nu.tar.gz --directory /tmp
    - cp "/tmp/$NUSHELL_BUILD/nu" /tmp/nu

    - nu --version

  script:
    - cargo check --workspace --all-targets
    - cargo clippy --workspace --all-targets -- -D warnings
    - cargo test --workspace --verbose
    - nu tests/cli.nu
    - nu tests/binary.nu
    - nu examples/cli.nu
