# WARNING: update `rust-toolchain.toml` as well
image: "rust:1.78"

stages:
  - fmt
  - test

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^(draft|no-ci):/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: ($CI_PIPELINE_SOURCE == "push") && ($CI_COMMIT_BRANCH == "main")

fmt:
  stage: fmt

  script:
    - make fmt-check

test:
  stage: test
  needs:
    - fmt
  before_script:
    - apt update --yes
    - apt upgrade --yes
    - apt install protobuf-compiler --yes
    - make show

  script:
    - make check clippy test
