[package]
name = "komodo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bls12-381 = "0.4.0"
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-poly = "0.4.2"
ark-poly-commit = "0.4.0"
ark-serialize = "0.4.2"
ark-std = "0.4.0"
reed-solomon-erasure = { git = "https://github.com/jdetchart/reed-solomon-erasure", branch = "master" }
rs_merkle = "1.4.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
