flowchart LR
    %% states
    file@{          shape: rounded  , label: "original file $$\\ F$$"        }
    source@{        shape: processes, label: "$$k\\ $$ source shards"        }
    encoded@{       shape: processes, label: "$$n\\ $$ encoded shards"       }

    gathered@{      shape: processes, label: "at least $$\\ k\\ $$ shards"   }
    decoded@{       shape: processes, label: "$$k\\ $$ decoded shards"       }
    reconstructed@{ shape: rounded  , label: "reconstructed file $$\\ F^*$$" }

    %% steps
    encoding(["$$(k, n)$$-encoding"])
    decoding(["$$k$$-decoding"])

    life_1@{ shape: framed-circle, label: "life" }
    life_2@{ shape: framed-circle, label: "life" }

    %% main
    file --- split(["split"]) --> source --- encoding --> encoded --- disseminate(["disseminate"]) --> life_1

    life_2 --- gather(["gather"]) --> gathered --- decoding --> decoded --- concat(["concat"]) --> reconstructed
