sequenceDiagram
    actor prover
    actor verifier

    Note over prover,verifier: generate public objects required<br/>for proving and verifying

    Note left of prover: encodes the data $$\ (s_i) = \texttt{encode}(\Delta)$$
    Note left of prover: computes commitment $$\ \mathcal{C} = \texttt{commit}(\Delta)$$
    Note left of prover: computes proof $$\ \pi_i = \texttt{prove}(s_i)$$

    prover->>verifier: $$\mathcal{C} \text{, } (\pi_i, s_i)$$

    Note right of verifier: verify that all $$\ (\mathcal{C} \text{, } \pi_i \text{, } s_i)\ $$ are consistent
