name: Rust CI

on: [push, pull_request, workflow_dispatch]

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/dragoon-rs/dragoon/komodo:8c58cba4ffc97c8e368de6c0c662617501e1ee51"
    if: "!contains(github.event.head_commit.message, 'draft:') && !contains(github.event.head_commit.message, 'no-ci:')"
    steps:
      - uses: actions/checkout@v3
      - run: ./make.rs ci --fmt

  test:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/dragoon-rs/dragoon/komodo:8c58cba4ffc97c8e368de6c0c662617501e1ee51"
    needs: fmt
    if: "!contains(github.event.head_commit.message, 'draft:') && !contains(github.event.head_commit.message, 'no-ci:')"
    steps:
      - uses: actions/checkout@v3
      - run: ./make.rs ci --test
