name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'draft:') && !contains(github.event.head_commit.message, 'no-ci:')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run fmt check
        run: make fmt-check

  test:
    runs-on: ubuntu-latest
    needs: fmt
    if: "!contains(github.event.head_commit.message, 'draft:') && !contains(github.event.head_commit.message, 'no-ci:')"
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update --yes
          sudo apt upgrade --yes
          sudo apt install protobuf-compiler --yes
      - name: Show configuration
        run: make show
      - name: Run tests
        run: |
          make check clippy test
