name: Rust CI

on: [push, pull_request, workflow_dispatch]

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/dragoon-rs/dragoon/komodo:406e2b0c1ca04443d9219fa2fbb07f62dc81c796"
    if: "!contains(github.event.head_commit.message, 'draft:') && !contains(github.event.head_commit.message, 'no-ci:')"
    steps:
      - uses: actions/checkout@v3
      - run: ./make.rs ci --fmt
      - run: ./scripts/check-lock-file.sh

  test:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/dragoon-rs/dragoon/komodo:406e2b0c1ca04443d9219fa2fbb07f62dc81c796"
    needs: fmt
    if: "!contains(github.event.head_commit.message, 'draft:') && !contains(github.event.head_commit.message, 'no-ci:')"
    steps:
      - uses: actions/checkout@v3
      - run: ./make.rs ci --test
      - run: ./scripts/check-lock-file.sh
