name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'draft:') && !contains(github.event.head_commit.message, 'no-ci:')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run fmt check
        run: make fmt-check

  test:
    runs-on: ubuntu-latest
    needs: fmt
    if: "!contains(github.event.head_commit.message, 'draft:') && !contains(github.event.head_commit.message, 'no-ci:')"
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update --yes
          sudo apt upgrade --yes
          sudo apt install protobuf-compiler --yes
      - name: Install Nushell
        run: |
          # looks like the following PATH export does not work and `NU` still needs to be set for some reason to invoke `make`...
          echo "PATH=\"$(make print-NU_DEST):$PATH\"" >> $GITHUB_ENV
          make install-nu
      - name: Show configuration
        run: make NU="$(make print-NU_DEST)/nu" show
      - name: Run tests
        run: |
          make NU="$(make print-NU_DEST)/nu" check clippy test example
