name: Rust CI

on: [push, pull_request, workflow_dispatch]

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/dragoon-rs/dragoon/komodo:bcb0e6b5f73420762f6208700a43291e0066c2c3"
    if: "!contains(github.event.head_commit.message, 'draft:') && !contains(github.event.head_commit.message, 'no-ci:')"
    steps:
      - uses: actions/checkout@v3
      - name: Run fmt check
        run: |
          ./make.rs fmt --check

  test:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/dragoon-rs/dragoon/komodo:bcb0e6b5f73420762f6208700a43291e0066c2c3"
    needs: fmt
    if: "!contains(github.event.head_commit.message, 'draft:') && !contains(github.event.head_commit.message, 'no-ci:')"
    steps:
      - uses: actions/checkout@v3
      - name: Show configuration
        run: |
          ./make.rs version
      - name: Run tests
        run: |
          ./make.rs check
          ./make.rs clippy
          ./make.rs test
